### ISSUE TITLE
ZeeQS with Hazelcast and Postgresql : Missing relation in Postgresql

### ISSUE THREAD

**Issue by vctrmn** [camunda-community-hub/zeeqs#191]
Hello everyone !

I am trying to run ZeeQS with Hazelcast and Postgresql in Kubernetes.
I first tried to run this Dockerfile :
```
version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:1.2.3
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../target/exporter/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
      
  zeeqs:
    container_name: zeeqs
    image: ghcr.io/camunda-community-hub/zeeqs:2.1.0
    environment:
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./lib/postgresql-42.2.12.jar:/app/libs/postgresql-42.2.12.jar
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - zeebe_network

  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - zeebe_network

volumes:
  database-data:
```

I have this error from Postgresql :
```
db_1     | 2021-11-29 18:08:01.484 UTC [33] ERROR:  relation "hazelcast_config" does not exist at character 82
db_1     | 2021-11-29 18:08:01.484 UTC [33] STATEMENT:  select hazelcastc0_.id as id1_3_0_, hazelcastc0_.sequence as sequence2_3_0_ from hazelcast_config hazelcastc0_ where hazelcastc0_.id=$1
```
And from ZeeQS : 
```
zeeqs    | 2021-11-29 18:08:01.499  WARN 1 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42P01
zeeqs    | 2021-11-29 18:08:01.500 ERROR 1 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: relation "hazelcast_config" does not exist
zeeqs    |   Position: 82
zeeqs    | 2021-11-29 18:08:01.510  INFO 1 --- [           main] o.h.e.internal.DefaultLoadEventListener  : HHH000327: Error performing load command
zeeqs    | 
zeeqs    | org.hibernate.exception.SQLGrammarException: could not extract ResultSet
...
zeeqs    | Caused by: org.postgresql.util.PSQLException: ERROR: relation "hazelcast_config" does not exist
```

There is a missing relation in Postgresql
