### ISSUE TITLE
Zeebe User Task

### ISSUE THREAD

**Issue by ZeyadDev** [camunda-community-hub/zeeqs#491]
## Description
Zeebe 8.5.0 has introduced [Zeebe User Task](https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#define-a-user-task).

When I query Zeeqs Graphql, it returns BPMN User Task but **NOT** Zeebe User Task.

I am using docker compose as follows:

```yml
zeebe: 
    image: docker.core.dev/camunda/zeebe:8.5.0
    ports:
      - "8080:8080"
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    environment: 
      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=exporters/zeebe-hazelcast-exporter-1.4.0-jar-with-dependencies.jar
      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME=io.zeebe.hazelcast.exporter.HazelcastExporter
      - ...
    volumes:
      - zeebe:/usr/local/zeebe/data
      - ./exporters:/usr/local/zeebe/exporters:ro

  zeeqs:
    image: ghcr.io/camunda-community-hub/zeeqs:latest
    environment:
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - ...
    ports:
      - "9000:9000"
```
